# Default values for Microservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: cvnaimagesdev.azurecr.io
  pullPolicy: Always
  name: carvana-edge-MarketMap.UI
  portname: containerhttp

metadata:
  namespace: edge # Changing this value can be dangerous
  
terminationGracePeriodSeconds: 30

rollout:
  maxSurge: 2
  maxUnavailable: 0
  
hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

service:
  type: ClusterIP
  port: 80
  targetport: 3001
  portname: servicehttp
  livenessUrl: 
  readinessUrl: 
  livenessTimeout: 10
  livenessInitialDelay: 45
  livenessPeriod: 120
  readinessTimeout: 10
  readinessInitialDelay: 45
  readinessPeriod: 120

ingress:
  path: /MarketMap.UI/

resources:
  requests:
    memory: 750Mi
    cpu: 250m
  limits:
    memory: 750Mi
    cpu: 250m

environment: TEST

pdb:
  maxUnavailable: 1