apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-minion
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Chart.Name }} rewrite=/" # super thanks to https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/rewrites
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: "/{{ .Values.metadata.namespace }}{{ .Values.ingress.path }}"
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.service.port }}