apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
