apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.portname }}
    name: {{ .Values.service.portname }}
  selector:
    app: {{ .Chart.Name }}
